name: Validate PR Source

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [[ "${{ github.head_ref }}" != "develop" ]]; then
            echo "PR to main must come from develop"
            exit 1
          fi
